### ISSUE TITLE
Error regarding new dbplyr (v1.3.0.9000) changes

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/Organism.dplyr#17]
There is an error that is occurring in the tests due to new changes to dbplyr. The tests give the following:

```
         ERROR
        Running the tests in ‘tests/testthat.R’ failed.
        Last 13 lines of output:
          [32] 95456 - 95461 == -5
          [33] 95456 - 95461 == -5
          [34] 95456 - 95461 == -5
          [35] 95456 - 95461 == -5
          [47] 95461 - 95456 ==  5
          ...
   
          ══ testthat results
    ═════════════════════════════════════════════════════════════════════════
          OK: 200 SKIPPED: 0 FAILED: 1
          1. Failure: select (@test-src_organism-select.R#44)
   
          Error: testthat unit tests failed
          In addition: Warning message:
          call dbDisconnect() when finished working with a connection
          Execution halted
```

**Comment by dvantwisk** [comment]
AN update on this issue. The keys between the rs_src and rs_txdb file are the same, the only issue is that the ordering is off. Ordering rs_src by its tx_name table corrects the issue, the problem is that it's not clear what column to order on correct this. Maybe since the two tables are identical except the ordering is off, this isn't a problem at all and we can fix the test by simply applying an ordering after the select() calls in the test. Should I try to fix this code inside the select_tbl() function or just write a test that is order ambiguous? @mtmorgan

**Comment by mtmorgan** [comment]
return the columns in an order that is consistent with 'endomorphic' expectations on 'select' columns, and write a test that is stringent enough but not too stringent; hope this is helpful.

If the dbplyr `select()` is not endomorphic on column names in the selection, then I think that is worth an issue there (though maybe it has already come up and been addressed philosophically rather than practically).

**Comment by dvantwisk** [comment]
I've looked through the GenomicFeatures select() and found that it actually does order on `keytype` to solve a similar issue. Performing this same ordering operation seems to fix the issue in Organism.plyr's select without changing the tests. We'll see if it builds alright on the build system and I will close this issue for now.
