### ISSUE TITLE
`exonsBy()` and others don't return same columns as GRanges version

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/Organism.dplyr#9]
E.g., in test-src_organims-class.R, "mouse" test

```
> names(mcols(exonsBy(src)[[1]]))
Joining, by = c("ensembl", "tx_id")
[1] "tx_id"     "exon_id"   "exon_name" "exon_rank"
> names(mcols(exonsBy(txdb)[[1]]))
[1] "exon_id"   "exon_name" "exon_rank"
```

**Comment by yubocheng** [comment]
"tx_id" is needed to convert GRanges to GRangesList using split, line 340 in extractors.R, trying to drop "tx_id" after GRangesList is generated, but haven't found a way yet.

**Comment by mtmorgan** [comment]
One way is to make a copy of the vector and update the GRanges before splitting, e.g., at https://github.com/Bioconductor/Organism.dplyr/blob/master/R/extractors.R#L342

```
grp <- mcols(table)[[f]]
mcols(table)[[f]] <- NULL
split(table, grp)
```
